# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000

development:
  <<: *default
  database:  wizehoot_development

test:
  <<: *default
  database: wizehoot_test

production:
  <<: *default
  database: wizehoot_production
  username: wizehoot
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
